CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, email text UNIQUE NOT NULL, password_hash text NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS conversations (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, project_id uuid REFERENCES projects(id) ON DELETE SET NULL, title text NOT NULL, summary text DEFAULT '', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS messages (id uuid PRIMARY KEY, conversation_id uuid REFERENCES conversations(id) ON DELETE CASCADE, role text NOT NULL, content text NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS memories (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, project_id uuid REFERENCES projects(id) ON DELETE CASCADE, kind text NOT NULL, content text NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS files (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, project_id uuid REFERENCES projects(id) ON DELETE CASCADE, name text NOT NULL, mime text, content text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS chunks (id uuid PRIMARY KEY, file_id uuid REFERENCES files(id) ON DELETE CASCADE, content text NOT NULL, embedding vector(768), created_at timestamptz DEFAULT now());
CREATE INDEX IF NOT EXISTS chunks_embedding_idx ON chunks USING hnsw (embedding vector_cosine_ops);
