"use client";
import {useEffect,useRef,useState} from "react";
type Msg={role:"user"|"assistant";content:string};
export default function Home(){
const [messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState<any>(null),[file,setFile]=useState<File|null>(null);
const abortRef=useRef<AbortController|null>(null);
useEffect(()=>{fetch("/api/health").then(r=>r.json()).then(setStatus).catch(()=>setStatus({ok:false}));},[]);
async function send(){const text=input.trim();if(!text||busy)return;const next=[...messages,{role:"user" as const,content:text}];setMessages([...next,{role:"assistant",content:""}]);setInput("");setBusy(true);const ac=new AbortController();abortRef.current=ac;try{const r=await fetch("/api/ai/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:next,stream:true}),signal:ac.signal});if(!r.ok)throw new Error((await r.text())||"AI server error");const reader=r.body?.getReader();if(!reader)throw new Error("Streaming unavailable");const dec=new TextDecoder();let out="";while(true){const x=await reader.read();if(x.done)break;for(const line of dec.decode(x.value,{stream:true}).split("\n").filter(Boolean)){const j=JSON.parse(line);if(j.error)throw new Error(String(j.error));out+=j.message?.content||"";setMessages(m=>{const c=[...m];c[c.length-1]={role:"assistant",content:out};return c;});}}}catch(e){setMessages(m=>{const c=[...m];c[c.length-1]={role:"assistant",content:"Fehler: "+(e instanceof Error?e.message:"Unbekannter Fehler")};return c;});}finally{setBusy(false);abortRef.current=null;}}
function stop(){abortRef.current?.abort();setBusy(false)}
async function upload(){if(!file)return;const fd=new FormData();fd.append("file",file);const r=await fetch("/api/files/extract",{method:"POST",body:fd});const j=await r.json();if(r.ok){setInput(v=>v+"\n[Datei: "+j.name+"]\n"+j.text.slice(0,12000));setFile(null)}else alert(j.error||"Datei konnte nicht gelesen werden.")}
return <main className="shell"><aside className="side"><div className="brand"><span>◈</span> ABDULS AI</div><button onClick={()=>setMessages([])}>＋ Neuer Chat</button><nav><div>Chats</div><div>Projekte</div><div>Dateien</div><div>Modelle</div><div>Einstellungen</div></nav><div className="status">{status?.ok?"● Lokale KI online":"○ KI-Server nicht erreichbar"}</div></aside><section className="chat"><header><div><b>ABDULS AI</b><small>Self-hosted AI Workspace</small></div><span>{status?.capabilities?.chat?"Local model":"Offline"}</span></header><div className="messages">{messages.length===0?<div className="welcome"><h1>Was möchtest du bauen?</h1><p>Code, Dateien, Recherche und lokale KI.</p></div>:messages.map((m,i)=><article className={m.role} key={i}><div className="bubble">{m.content}</div>{m.role==="assistant"&&i===messages.length-1&&busy?<small>generiert…</small>:null}</article>)}</div><div className="composer">{file&&<div className="filebar">{file.name}<button onClick={()=>setFile(null)}>×</button></div>}<textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Schreib etwas an ABDULS AI…" rows={3}/><div className="actions"><label>＋ Datei<input type="file" hidden accept=".pdf,.docx,.xlsx,.csv,.txt,.json,.md,.py,.js,.ts,.tsx,.jsx,.css,.html" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{file&&<button onClick={upload}>Datei einlesen</button>}<button className="send" onClick={busy?stop:send}>{busy?"Stop":"Senden"}</button></div></div></section></main>}
}