"use client";
import {FormEvent,useState} from "react";
type Msg={role:"user"|"assistant";content:string};
export default function Home(){
 const [messages,setMessages]=useState<Msg[]>([]);
 const [input,setInput]=useState(""); const [busy,setBusy]=useState(false);
 async function send(e?:FormEvent){e?.preventDefault();const text=input.trim();if(!text||busy)return;setInput("");setMessages(x=>[...x,{role:"user",content:text}]);setBusy(true);
 try{const r=await fetch("/api/ai/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text})});const d=await r.json();setMessages(x=>[...x,{role:"assistant",content:d.message??"Keine Antwort."}]);}catch{setMessages(x=>[...x,{role:"assistant",content:"Der self-hosted AI-Server ist nicht erreichbar."}]);}finally{setBusy(false)}}
 return <div className="app"><aside className="sidebar"><div className="brand">ABDULS <span>AI</span></div><button className="new" onClick={()=>setMessages([])}>+ Neuer Chat</button><nav className="nav"><button>Chats</button><button>Projekte</button><button>Dateien</button><button>Modelle</button><button>Einstellungen</button></nav><div className="status"><span className="dot"/>Self-hosted Gateway</div></aside><main className="main"><header className="top"><span>ABDULS AI</span><span className="model">Lokale Inferenz</span></header><section className="workspace"><div className="hero"><h1>Was möchtest du bauen?</h1><p>Chat, Code, Dateien, Vision und Projekte in einem lokalen AI Workspace.</p></div><div className="messages">{messages.length===0?<><div className="empty">Starte einen Chat.</div><div className="featureGrid"><div className="card"><b>Code</b><small>Coding-Agent und Workspace</small></div><div className="card"><b>Dateien</b><small>Lokale Dateien und RAG</small></div><div className="card"><b>Vision</b><small>Bilder, Screenshots und OCR</small></div></div></>:messages.map((m,i)=><div key={i} className={"message "+m.role}>{m.content}</div>)}</div><form className="composer" onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Schreibe an ABDULS AI..." /><div className="composerRow"><div className="tools"><button type="button">Datei</button><button type="button">Bild</button><button type="button">Tools</button></div><button className="send" disabled={busy}>{busy?"...":"Senden"}</button></div></form></section></main></div>
}